### ISSUE TITLE
After update sql tables updates broke?

### ISSUE THREAD

**Issue by ipro4911** [DeKaDeNcE/WoWCore#5]
as tittle might suggest i have wierd problem where after update sql tables if theres a update sql it doesnt get applied effectively giving error but need to reset all to fresh to able to start,just minor detail l hope its not

**Comment by ipro4911** [comment]
and for 10.1 seems its really early to able to use branch and trying to rebuild from command line as it gives 7 errors

**Comment by ZaDarkSide** [comment]
I guess the issues are solved.

**Comment by ipro4911** [comment]
example happens at 2nd time u run bnetserver.exe 
![image](https://github.com/DeKaDeNcE/WoWCore/assets/105972244/dc43bd8e-7216-49af-ba0d-acee92037bc0)

**Comment by ZaDarkSide** [comment]
This issue is now fixed, thanks for reporting it.

**Comment by ipro4911** [comment]
The cause is old folder and still broken after i open it after rebuilding it

**Comment by ZaDarkSide** [comment]
> 

you need to clone again whole repo most likely

**Comment by ipro4911** [comment]
if i rename old to old1 it works like charm
